### ISSUE TITLE
프론트 현황

### ISSUE THREAD

**Issue by emitlight** [OreumiTeam4242/4242#19]
- 신청글 목록: HTML, CSS 완료 

- 관리자(신고글) 목록: HTML 완료, CSS는 주원님이 해주셨습니다.

- 개인정보 페이지: HTML 완료, CSS 완료

- 개인정보 수정 페이지: HTML 완료, CSS 완료
> 완료했습니다.

**Comment by JuwoenLee** [comment]
👏👏👏

**Comment by emitlight** [comment]
Issue Close
