### ISSUE TITLE
디티오 관련 확인사항

### ISSUE THREAD

**Issue by Eunji1217** [OreumiTeam4242/4242#23]
우선 공통 디티오로 되어있지만 역할 분담후 맡은 파트 작업하면서
DTO -> requestDto , responseDto
ex) postDTO -> postRequestDto, postResponseDto
이런식으로 두개로 분리해서 작업합시다!

**Comment by emitlight** [comment]
알겠습니다~

**Comment by drinkgalaxy** [comment]
넵!
