### ISSUE TITLE
파일 이미지 관련

### ISSUE THREAD

**Issue by Eunji1217** [OreumiTeam4242/4242#30]
1. 우선 컨트롤러 -> 분리할 것인가 합칠것인가에 대해 고민해봤는데 우선 붙이는게 작업하기엔 편해보입니ㅏㄷ..! 일단 test 용으로 분리해놨지만.. 나중에 제가 합치겠습니다
2. 조회 관련 -> 얘도 위와 같은 이유로 저장이 string -path 로 되기때문에 파일이 필요한 각각에 엔티티에 관하여 그냥 경로만 넣어주고 다른 엔티티 조회할때 같이 보여주면 될 것 같습니다...
3. 멤버 매핑은 다같이있을때 한번 더해서 해볼게여!
다른 기능들 우선 구현 총총총..

**Comment by drinkgalaxy** [comment]
넵 확인했습니다!
