### ISSUE TITLE
use_yn 사용건에 대하여

### ISSUE THREAD

**Issue by Eunji1217** [OreumiTeam4242/4242#33]
repository -> delete 를 사용하지 않고 use_yn 사용을 해서 해당 데이터 사용을 못하게 하기... 이 방법에 대해선 더 자세하게 토론해봐야할 것 같습니다!

**Comment by JuwoenLee** [comment]
post에서는 우선 team이랑 연결되었어서 yse_yn을 false로 바꿔서 사용했습니당

**Comment by JuwoenLee** [comment]
soft delete
삭제로 인정~~
![image](https://github.com/OreumiTeam4242/4242/assets/82970714/41818923-f751-4c43-8521-ac9ab611ce7c)
