### ISSUE TITLE
백엔드 관련 일 남은 것도 정리

### ISSUE THREAD

**Issue by Eunji1217** [OreumiTeam4242/4242#90]
<개발>
1. 페이지네이션 구현 
2. 팀 (진행중인 스터디팀) 종료시 모집글 use_yn 0 처리하기
3.  ... 우선 기억나는건 여기까지

<문서>
1. erd 수정
2. api 명세서 뽑기 (swagger로 해올게요)
3. 이 문서들 기반으로 깃허브 리드미 수정

**Comment by drinkgalaxy** [comment]
오 swagger~ 좋습니다!!

**Comment by JuwoenLee** [comment]
쥬아요~~~(너덜너덜)

**Comment by Eunji1217** [comment]
페이지네이션은 완료...

**Comment by Eunji1217** [comment]
팀도 완료!

**Comment by Eunji1217** [comment]
완료~
